#!/usr/bin/env bash
export AWS_ACCESS_KEY_ID='AKIAII52CLCS24MEZM4A'
export AWS_SECRET_ACCESS_KEY='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'
./ec2_validate.py
[ $? -ne 0 ] && echo -e "\n\nError: something went wrong\n"

export AWS_ACCESS_KEY_ID='AKIAI4FLFVEXDEYPZUEA'
export AWS_SECRET_ACCESS_KEY='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'

./ec2_validate.py
[ $? -ne 0 ] && echo -e "Error: something went wrong\n"
